"""
LDPC codes: construction, encoding, decoding, and finding where the codewords start in a bit stream.

What is and is not blind here (be exact when explaining it):
  * The PARITY-CHECK MATRIX H defines an LDPC code. It cannot be recovered from a noisy stream in practice, so the
    decoder works from a library of known matrices: the built-in demo codes below, plus any matrix the operator uploads
    (alist or plain text). Which code is present, and where the codewords start, ARE found automatically.
  * Test for a code: the share of parity checks a block violates. Random bits violate about half of them; a block of
    the right code at the right start offset violates few. That share is searched over every start offset.
  * Decoder: normalised min-sum belief propagation on hard bits (the receiver passes hard decisions on).

Built-in codes are "IRA" codes (systematic, dual-diagonal parity part, so encoding is a cheap accumulation) whose
information part is generated by a seeded 4-cycle-avoiding construction. They are NOT the CCSDS / 5G / DVB-S2 codes,
whose tables are not reproduced here: to decode those, upload their H matrix.

Convention for uploaded matrices: systematic code, information bits first (k = n - rows of H).
"""
import re

import numpy as np

# name: (n, k, seed, column weight of the information part)
BUILTIN = {
    "ldpc_256_128": (256, 128, 11, 3),
    "ldpc_512_256": (512, 256, 12, 3),
    "ldpc_1024_512": (1024, 512, 13, 3),
}
ALPHA = 0.8                                     # min-sum normalisation
MAX_ITER = 60


class LDPC:
    def __init__(self, H_rows, n, name="custom", source="uploaded", encodable=None):
        """H_rows: list of arrays of column indices, one per parity check."""
        self.name, self.source, self.n = name, source, int(n)
        self.rows = [np.array(sorted(set(int(c) for c in r)), np.int64) for r in H_rows if len(r)]
        self.m = len(self.rows)
        self.k = self.n - self.m
        if self.k <= 0:
            raise ValueError("H must have fewer rows than columns")
        self.dmax = max(len(r) for r in self.rows)
        # padded check layout; pad index = n (a dummy position that always holds 0)
        self.R = np.full((self.m, self.dmax), self.n, np.int64)
        for i, r in enumerate(self.rows):
            self.R[i, :len(r)] = r
        self.pad = self.R == self.n
        # variable -> edge layout (flat edge id = row * dmax + slot); pad edge id = m * dmax (a dummy zero edge)
        per_var = [[] for _ in range(self.n)]
        for i, r in enumerate(self.rows):
            for s, c in enumerate(r):
                per_var[c].append(i * self.dmax + s)
        self.dv = max(len(v) for v in per_var)
        self.VE = np.full((self.n, self.dv), self.m * self.dmax, np.int64)
        for c, v in enumerate(per_var):
            self.VE[c, :len(v)] = v
        self.rate = self.k / self.n
        self.encodable = encodable                     # (H1 dense, ) for built-in IRA codes
        self.col_weights = np.array([len(v) for v in per_var])

    def info(self):
        return dict(name=self.name, n=self.n, k=self.k, rate=f"{self.k}/{self.n}", checks=self.m,
                    source=self.source, max_check_degree=int(self.dmax), max_var_degree=int(self.dv))

    # ------------------------------------------------------------ syndrome
    def syndrome(self, blocks):
        """blocks: (nb, n) 0/1. Returns (nb, m) uint8, 1 = check violated."""
        ext = np.concatenate([blocks.astype(np.uint8), np.zeros((blocks.shape[0], 1), np.uint8)], axis=1)
        return np.bitwise_xor.reduce(ext[:, self.R], axis=2)

    # ------------------------------------------------------------ encoding (built-in codes)
    def encode(self, info_bits):
        """info_bits: 1-D, padded with zeros to a multiple of k. Returns the concatenated codewords [info | parity]."""
        if self.encodable is None:
            raise ValueError("this code has no encoder (uploaded matrices are decode-only)")
        H1 = self.encodable
        u = np.asarray(info_bits, np.uint8)
        pad = (-len(u)) % self.k
        if pad:
            u = np.concatenate([u, np.zeros(pad, np.uint8)])
        U = u.reshape(-1, self.k)
        s = (U.astype(np.int32) @ H1.T.astype(np.int32)) & 1             # (nb, m)
        p = np.bitwise_xor.accumulate(s.astype(np.uint8), axis=1)
        return np.concatenate([U, p], axis=1).reshape(-1)

    # ------------------------------------------------------------ decoding
    def decode(self, blocks, max_iter=MAX_ITER, alpha=ALPHA):
        """Normalised min-sum on hard-decision input. blocks: (nb, n) 0/1.
        Returns (decoded (nb,n) uint8, ok (nb,) bool, iterations (nb,))."""
        nb = blocks.shape[0]
        out = blocks.astype(np.uint8).copy()
        ok = self.syndrome(out).sum(axis=1) == 0
        iters = np.zeros(nb, int)
        todo = np.where(~ok)[0]
        if len(todo) == 0:
            return out, ok, iters
        ch = (1.0 - 2.0 * blocks[todo].astype(np.float32))                 # +1 = bit 0, -1 = bit 1
        T = len(todo)
        Mc = np.zeros((T, self.m * self.dmax + 1), np.float32)             # check->variable messages (+ dummy slot)
        active = np.arange(T)
        for it in range(1, max_iter + 1):
            a = active
            # variable totals
            total = ch[a] + Mc[a][:, self.VE].sum(axis=2)                    # (A, n)
            tot_ext = np.concatenate([total, np.zeros((len(a), 1), np.float32)], axis=1)
            V = tot_ext[:, self.R] - Mc[a][:, :-1].reshape(len(a), self.m, self.dmax)   # variable->check
            V[:, self.pad] = 1e6                                             # pads never win a minimum
            sgn = np.where(V < 0, -1.0, 1.0).astype(np.float32)
            sgn[:, self.pad] = 1.0
            mag = np.abs(V)
            idx1 = mag.argmin(axis=2)
            min1 = np.take_along_axis(mag, idx1[..., None], axis=2)
            mag2 = mag.copy()
            np.put_along_axis(mag2, idx1[..., None], 1e9, axis=2)
            min2 = mag2.min(axis=2, keepdims=True)
            sprod = sgn.prod(axis=2, keepdims=True)
            use2 = np.arange(self.dmax)[None, None, :] == idx1[..., None]
            newM = alpha * sprod * sgn * np.where(use2, min2, min1)
            newM[:, self.pad] = 0.0
            Mc[a, :-1] = newM.reshape(len(a), -1)
            total = ch[a] + Mc[a][:, self.VE].sum(axis=2)
            hard = (total < 0).astype(np.uint8)
            good = self.syndrome(hard).sum(axis=1) == 0
            out[todo[a]] = hard
            if good.any():
                done = todo[a][good]
                ok[done] = True
                iters[done] = it
                active = a[~good]
            if len(active) == 0:
                break
        iters[todo[~ok[todo]]] = max_iter
        return out, ok, iters

    # ------------------------------------------------------------ where do codewords start?
    def align(self, bits, n_blocks=4):
        """Share of violated checks for every possible start offset 0..n-1, using n_blocks consecutive blocks.
        Returns (best_offset, best_fraction, z_score_vs_random)."""
        bits = np.asarray(bits, np.uint8)
        need = (n_blocks + 1) * self.n
        if len(bits) < need:
            n_blocks = len(bits) // self.n - 1
            if n_blocks < 2:
                return 0, 0.5, 0.0
        ext = np.concatenate([bits, np.zeros(1, np.uint8)])
        zero = len(bits)
        fr = np.empty(self.n)
        offs = np.arange(self.n)
        chunk = max(8, int(4e6 // max(1, n_blocks * self.m * self.dmax)))
        for s in range(0, self.n, chunk):
            o = offs[s: s + chunk]
            acc = np.zeros(len(o))
            for b in range(n_blocks):
                idx = o[:, None, None] + b * self.n + self.R[None]                    # (O, m, dmax)
                idx = np.where(self.pad[None], zero, idx)
                acc += np.bitwise_xor.reduce(ext[idx], axis=2).mean(axis=1)
            fr[s: s + chunk] = acc / n_blocks
        best = int(fr.argmin())
        sd = 0.5 / np.sqrt(self.m * n_blocks)
        return best, float(fr[best]), float((0.5 - fr[best]) / sd)


# ====================================================================== construction of built-in codes
def _build_builtin(name):
    n, k, seed, cw = BUILTIN[name]
    return make_ira(n, k, seed, cw, name=name, source="built-in")


def make_ira(n, k, seed, cw=3, name="custom_ira", source="generated"):
    """Seeded systematic IRA code (dual-diagonal parity part). Used for the built-in codes and in tests."""
    m = n - k
    rng = np.random.default_rng(seed)
    cols = []                                       # each info column = tuple of check indices
    rdeg = np.zeros(m, int)
    taken = [set() for _ in range(m)]               # for every check, the info columns already using it
    for c in range(k):
        for attempt in range(400):
            order = np.lexsort((rng.random(m), rdeg))           # least-loaded checks first, random among ties
            pick = list(order[: cw * 3 if attempt < 200 else m])
            rng.shuffle(pick)
            chosen = []
            for r in pick:
                if r in chosen:
                    continue
                # avoid 4-cycles: a new pair of checks must not already share another column
                bad = False
                for q in chosen:
                    if taken[r] & taken[q]:
                        bad = True
                        break
                if not bad:
                    chosen.append(r)
                if len(chosen) == cw:
                    break
            if len(chosen) == cw:
                break
        for r in chosen:
            taken[r].add(c)
            rdeg[r] += 1
        cols.append(chosen)
    H1 = np.zeros((m, k), np.uint8)
    for c, rs in enumerate(cols):
        H1[rs, c] = 1
    rows = []
    for i in range(m):
        r = list(np.where(H1[i])[0]) + [k + i]                  # staircase parity part: p_i appears in rows i and i+1
        if i > 0:
            r.append(k + i - 1)
        rows.append(r)
    return LDPC(rows, n, name=name, source=source, encodable=H1)


_CACHE = {}


def get_builtin(name):
    if name not in _CACHE:
        _CACHE[name] = _build_builtin(name)
    return _CACHE[name]


def builtin_library():
    return [get_builtin(nm) for nm in BUILTIN]


def to_alist(code):
    """Standard alist text of a code's parity-check matrix (so a built-in code can be saved and re-uploaded)."""
    cols = [[] for _ in range(code.n)]
    for i, r in enumerate(code.rows):
        for c in r:
            cols[c].append(i + 1)
    out = [f"{code.n} {code.m}", f"{max(len(c) for c in cols)} {code.dmax}",
           " ".join(str(len(c)) for c in cols), " ".join(str(len(r)) for r in code.rows)]
    out += [" ".join(map(str, c)) for c in cols]
    out += [" ".join(str(int(c) + 1) for c in r) for r in code.rows]
    return "\n".join(out) + "\n"


# ====================================================================== reading an uploaded matrix
def parse_matrix(text, name="uploaded"):
    """Accepts (1) alist format, (2) a dense 0/1 matrix, one row per line (digits optionally space separated),
    (3) sparse text with one 'row col' pair per line (0-based), optionally after a header line 'rows cols'."""
    lines = [ln.strip() for ln in text.replace("\r", "").split("\n") if ln.strip() and not ln.strip().startswith("#")]
    if not lines:
        raise ValueError("empty file")
    first = lines[0].split()
    nums = [t for t in first if re.fullmatch(r"\d+", t)]
    if len(first) == 2 and len(nums) == 2 and all(len(re.findall(r"\d+", ln)) >= 1 for ln in lines):
        # alist (n m header, then maximum degrees) or 'rows cols' header
        n, m = int(first[0]), int(first[1])
        if len(lines) >= 4 and len(lines[1].split()) == 2 and len(lines[2].split()) == n and len(lines[3].split()) == m:
            # alist: lines 4.. n column lists, then m row lists. The row lists are enough.
            row_lines = lines[4 + n: 4 + n + m]
            rows = [[int(t) - 1 for t in ln.split() if int(t) > 0] for ln in row_lines]
            if len(rows) != m:
                raise ValueError("alist: expected %d row lines" % m)
            return LDPC(rows, n, name=name)
    # dense 0/1
    if all(re.fullmatch(r"[01 ,]+", ln) for ln in lines):
        mat = [[int(ch) for ch in re.findall(r"[01]", ln)] for ln in lines]
        w = {len(r) for r in mat}
        if len(w) != 1:
            raise ValueError("dense matrix rows have different lengths")
        n = w.pop()
        return LDPC([[j for j, v in enumerate(r) if v] for r in mat], n, name=name)
    # sparse pairs
    pairs = []
    hdr = None
    for i, ln in enumerate(lines):
        t = re.findall(r"\d+", ln)
        if len(t) == 2:
            if i == 0 and False:
                hdr = t
            pairs.append((int(t[0]), int(t[1])))
        else:
            raise ValueError("could not read line %d: expected two numbers" % (i + 1))
    if hdr is None and pairs:
        # treat first line as a 'rows cols' header when it is larger than every other pair would allow
        m0, n0 = pairs[0]
        rest = pairs[1:]
        if rest and m0 > max(r for r, _ in rest) and n0 > max(c for _, c in rest):
            pairs, n = rest, n0
        else:
            n = max(c for _, c in pairs) + 1
    m = max(r for r, _ in pairs) + 1
    rows = [[] for _ in range(m)]
    for r, c in pairs:
        rows[r].append(c)
    return LDPC(rows, n, name=name)


# ====================================================================== identification in a stream
SAT_MAX = 0.40          # a block of the right code at the right offset violates fewer than this share of checks
Z_MIN = 7.0             # ... and the gap from 0.5 must be this many standard deviations of a random block


def identify(bits, library, n_blocks=4):
    """Search the library. Returns the best hit dict (code, offset, sat_fraction, z) or None."""
    best = None
    for code in library:
        if len(bits) < 3 * code.n:
            continue
        off, fr, z = code.align(bits, n_blocks=n_blocks)
        if fr < SAT_MAX and z >= Z_MIN and (best is None or z > best["z"]):
            best = dict(code=code, offset=off, sat_fraction=fr, z=z)
    return best


def decode_stream(bits, code, offset):
    """Decode every whole block from `offset`. Returns dict with info bits (first k of each block) and statistics."""
    bits = np.asarray(bits, np.uint8)
    nb = (len(bits) - offset) // code.n
    blk = bits[offset: offset + nb * code.n].reshape(nb, code.n)
    dec, ok, iters = code.decode(blk)
    # blocks that did not converge keep the best guess; they are reported
    corrected = int((dec != blk).sum())
    return dict(info=dec[:, :code.k].reshape(-1), n_blocks=int(nb), converged=int(ok.sum()), failed=int((~ok).sum()),
                corrected_bits=corrected, mean_iterations=round(float(iters[ok].mean()), 1) if ok.any() else None,
                channel_ber=round(corrected / max(1, nb * code.n), 5))
